version: "3.9"

services:
  frontend:
    build:
      context: ../project-frontend-remix
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      API_URL: http://localhost:3000
      PORT: 8080

  backend:
    build:
      context: ../project-backend-golang
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password

  db:
    build:
      context: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
